### PR TITLE
Add support for input placeholders

### PR DESCRIPTION
**Pull request by eanlain**
Calculates and stores the width of the input's placeholder, if there is any present. Will set the minimum width to the placeholder width value when input value is empty (length of 0).

This commit (line 54) also fixes an issue where an input with no value is initialized to 100% of the containing div instead of the width of a placeholder (if defined).

### CODE REVIEW

**Comment by MartinF** [comment]
Thanks for the contribution.

I actually previously removed the support for placeholders because I thought it shouldn't act according to the placeholder value as it is not user input.

But maybe it should be added again - I can see other request it as well.

**Comment by matthew-kerle** [comment]
I would suggest re-adding it, along with the ability to toggle it with an options = {} sort of object on instantiation. I was going to write my own version of it, but I was so surprised that your function doesn't take placeholders into account I was browsing your repo in more depth and found this.

**Comment by eanlain** [comment]
@Labradoodle-360, just added the semi-colons.

**Comment by matthew-kerle** [comment]
So...I implemented this on a service I'm working on, and it didn't work. The "syntax fix" you changed for: && value != 0 to && value !== 0 broke it. Removing the extra = makes the script work for me. Maybe there's a strict reason why you wanted to use == (I can't see one off the top of my head), but a better approach might be && this._placeholder != "" that way it will still return; if there's a placeholder, but it's empty (which is also possible). Good work though man.

**Comment by eanlain** [comment]
Hmm, originally I had the !== but found that it broke, so the syntax fix commit reverted to the !=. That's currently out there right now:

https://github.com/eanlain/jQuery.Autosize.Input/blob/master/jquery.autosize.input.js#L54

**Comment by MartinF** [comment]
Thanks.
I am currently out travelling which is why I am not very active here.
I will try to see if I can find someone willing to help out.

**Pull request closed without merging**
